apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-iscreen
  labels:
    app: nextjs-iscreen
spec:
  selector:
    matchLabels:
      app: nextjs-iscreen
      tier: web
  template:
    metadata:
      labels:
        app: nextjs-iscreen
        tier: web
    spec:
      containers:
      - name: nextjs-iscreen-app
        image: gcr.io/devenv-215523/iscreen-ui:${SERVICE_VERSION}
        ports:
        - containerPort: 3000
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: nextjs-iscreen-cert
spec:
  domains:
    - igscreen.org
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-iscreen
  annotations:
    kubernetes.io/ingress.global-static-ip-name: iscreen-new-api-external-ip
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/managed-certificates: nextjs-iscreen-cert
  labels:
    app: nextjs-iscreen
spec:
  defaultBackend:
    service:
      name: nextjs-iscreen-backend
      port:
        number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-iscreen-backend
  labels:
    app: nextjs-iscreen
spec:
  type: NodePort
  selector:
    app: nextjs-iscreen
    tier: web
  ports:
  - port: 8080
    targetPort: 3000